/* ==========================================================================
   projects-content.js — dados de cada projeto: identidade visual (accent,
   icon), storytelling curto (intro: motivation/built/numbers) exibido no
   topo da página de projeto, e o README completo (blocks) exibido abaixo,
   atrás do botão "Ver histórico técnico completo".
   Consumido pelo navegador (via <script>) e pelo script gerador de páginas
   em scripts/build-projects.js (via require).
   ========================================================================== */

const PROJECTS_CONTENT = {
  medistudy: {
    slug: 'medistudy',
    order: 1,
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v6M12 16v6M2 12h6M16 12h6"/><circle cx="12" cy="12" r="3"/></svg>',
    accent: '#e3b53f',
    accent2: '#7a2438',
    typeBadge: { pt: 'IA + Educação', en: 'AI + Education' },
    hook: { pt: '15 ferramentas viraram uma, moldada do jeito que ela estuda.', en: '15 tools became one, shaped to how she studies.' },
    cardMetric: { pt: '15 ferramentas viraram uma, moldada do jeito que ela estuda.', en: '15 tools became one, shaped to how she studies.' },
    link: { type: 'none', label: { pt: 'Em desenvolvimento', en: 'In development' } },
    readme: 'https://github.com/RyanDua11/medistudy',
    intro: {
      pt: {
        motivation: 'Acompanhando minha namorada na jornada de estudar Medicina, via ela usando mais de 10 ferramentas diferentes pra estudar: uma IA pra conversar, outra pra debater ideias, Anki pra flashcard, mais uma pra gerar imagem. Como ela tem TDAH, esse tanto de ferramenta espalhada dificultava ainda mais o foco. Construí o MediStudy pra juntar tudo isso num lugar só, e ir além: um sistema que aprende com as respostas dela e se adapta ao jeito dela estudar.',
        built: 'Flashcards com repetição espaçada e importador do Anki, dois modos de revisão pensados pro tempo real dela (revisão rápida de 5 minutos, véspera de prova), casos clínicos gerados por IA a partir da matéria escolhida, agenda de provas com cálculo de nota necessária, e histórico de evolução em gráfico. Mais de 150 testes automatizados cobrem a lógica de negócio, e o app já passou por duas fases de um redesign visual completo.',
        numbers: 'Em uso real desde as primeiras ferramentas prontas, não só planejado: mais de 150 testes automatizados, 16 issues do GitHub fechadas, e um redesign visual em fase avançada (2 de 5 fases já completas).',
      },
      en: {
        motivation: "Following my girlfriend through her Medicine studies, I saw her using more than 10 different tools just to study: one AI to talk to, another to debate ideas with, Anki for flashcards, another one to generate images. Since she has ADHD, that many scattered tools made it even harder to focus. I built MediStudy to bring all of that into one place, and go further: a system that learns from her answers and adapts to how she studies.",
        built: "Spaced-repetition flashcards with an Anki importer, two review modes built around her actual time (a 5-minute quick review, a night-before-the-exam mode), AI-generated clinical cases from a chosen subject, an exam calendar with a required-grade calculator, and an evolution history shown as charts. Over 150 automated tests cover the business logic, and the app has already gone through two phases of a full visual redesign.",
        numbers: "In real use since the first tools were ready, not just planned: over 150 automated tests, 16 closed GitHub issues, and a visual redesign in an advanced stage (2 of 5 phases already complete).",
      },
    },
    pt: {
      name: 'MediStudy',
      status: 'Em desenvolvimento ativo',
      blocks: [
        { t: 'p', text: 'Sempre tive fascínio por IA e o que ela é capaz de fazer de verdade. Um dia vi minha namorada abrindo mais de 15 ferramentas diferentes só pra dar conta de uma sessão de estudo: o Claude pra tirar dúvida, o Anki pra flashcard, o NotebookLM pra organizar anotação, três ferramentas separadas resolvendo um único problema. Pensei: por que não construir uma que englobe tudo isso, moldada exatamente no jeito que ela estuda, e no jeito que ela estuda com as amigas?' },
        { t: 'gallery', label: 'Como está hoje', items: [
          { src: 'screens/01-login.webp', caption: 'Tela de login do MediStudy' },
          { src: 'screens/02-home.png', caption: 'Home: sidebar, missão do dia e grid de ferramentas com estatísticas reais' },
          { src: 'screens/03-flashcards.png', caption: 'Flashcards: card de revisão virado, com painel de estatísticas' },
          { src: 'screens/04-casos-clinicos.png', caption: 'Casos Clínicos: caso gerado por IA com alternativas' },
        ] },
        { t: 'h2', text: 'O que eu construí até aqui' },
        { t: 'p', text: 'A base já está de pé: flashcards com repetição espaçada de verdade (o fator de facilidade de cada card sobe ou desce a cada resposta, mudando quando ele volta a aparecer), importador de baralho do Anki, dois modos de revisão pensados pro tempo real dela, revisão rápida de 5 minutos antes da aula e véspera de prova revisando a matéria inteira do mais difícil pro mais fácil. Os casos clínicos são gerados por IA de verdade, a partir da matéria escolhida, com alternativas, explicação da resposta certa, e histórico de acerto salvo. Além disso: agenda de provas com cálculo de quanto ela precisa tirar pra fechar a média, e histórico de evolução em gráfico.' },
        { t: 'p', text: 'A parte de arquitetura que mais me interessou resolver, até aqui, foi tirar a chamada de IA do navegador: os casos clínicos passam por uma função no Supabase antes de chegar na IA, então a chave de acesso nunca fica exposta no site publicado. É pouco vistoso pra quem usa, mas é a diferença entre um projeto que só funciona no meu computador e um que funciona pra ela de verdade, todo dia.' },
        { t: 'diagram', label: 'Como a arquitetura funciona hoje', nodes: [
          { title: 'Ação na aluna', desc: 'Ex.: pedir um caso clínico de uma matéria' },
          { title: 'Função no Supabase', desc: 'Recebe o pedido, guarda a chave de IA em segurança' },
          { title: 'IA gera o conteúdo', desc: 'Groq, modelo Kimi K2, devolve o caso clínico' },
          { title: 'Validação', desc: 'Formato da resposta é checado antes de salvar' },
          { title: 'Banco de dados', desc: 'Caso e histórico de acerto salvos pra aluna' },
        ] },
        { t: 'h2', text: 'Onde o compartilhamento entra (visão futura)' },
        { t: 'p', text: 'Nada disso existe ainda, é a próxima camada que quero construir: o plano nasceu pensando em grupo, porque é assim que ela estuda de verdade, com as amigas, em chamada. A ideia é uma aluna gerar um caso clínico e chamar o grupo pra debater dentro do próprio app, ou subir o PDF de uma aula/prova antiga e esse material virar contexto ligado ao professor daquela turma, pra próxima aluna da mesma turma já usar esse histórico pronto. Hoje isso é desenho, não código.' },
        { t: 'h2', text: 'Uma estimativa do que isso significa na prática' },
        { t: 'visual', label: 'Antes / Depois', text: 'Pra montar um caso clínico do jeito que ela fazia antes: prompt no ChatGPT, copiar pro grupo do WhatsApp, às vezes colar em outra IA pra revisar. Isso facilmente passava de 10 a 15 minutos por caso. Dentro do MediStudy, esse fluxo cai pra menos de um minuto, sem trocar de aba.' },
        { t: 'visual', label: 'Antes / Depois', text: 'Uma prova simulada específica de um professor, hoje, ela teria que montar sozinha, juntando material manualmente. Isso levaria facilmente mais de uma hora. Com o histórico do professor já acumulado, isso vira questão de segundos.' },
        { t: 'h2', text: 'Engenharia de custo, hoje e pra quando o compartilhamento existir' },
        { t: 'p', text: 'Hoje já penso nisso na única chamada de IA que existe: os casos clínicos passam pela Groq, que tem camada gratuita generosa, e reservo Claude pra funcionalidade que realmente justifique o custo, fora dessa camada gratuita, em vez de entrar por padrão em tudo que pede IA. Quando o compartilhamento em grupo existir, esse cuidado vira ainda mais necessário: se toda vez que alguém pedisse uma prova simulada a IA precisasse reler o histórico inteiro de PDFs do professor do zero, o consumo de token ia explodir rápido. Por isso já penso o banco não só como lugar de guardar dado, mas como parte da estratégia de custo: resumir e indexar o material uma vez, guardar o resumo, e só reler o PDF inteiro quando for estritamente necessário.' },
        { t: 'p', text: 'A visão é ir além do que já uso: uma camada própria de orquestração decidindo em tempo real qual entre várias LLMs deve responder cada pedido, sempre otimizando custo.' },
        { t: 'vision', text: 'A camada de orquestração multi-IA ainda está na fase de desenho, não de código.' },
        { t: 'h2', text: 'A parte difícil' },
        { t: 'p', text: 'Desenhar isso não foi só decidir funcionalidade, foi decidir o que a tela mostra e o que ela esconde. Na primeira versão eu queria colocar tudo visível: gráfico, número, progresso. Percebi que isso ia contra o motivo do projeto existir, que era simplificar, não adicionar mais uma camada de decisão pra quem já tá sobrecarregada estudando pra prova. Mudei a lógica pra reduzir decisão em vez de acumular informação na tela.' },
        { t: 'h2', text: 'Onde está hoje' },
        { t: 'status', text: 'Em desenvolvimento ativo, com várias ferramentas já em uso real: login, home, flashcards com repetição espaçada e importador do Anki, casos clínicos gerados por IA, agenda de provas, cálculo de nota e histórico de evolução em gráfico. Mais de 150 testes automatizados cobrem a lógica de negócio, e o redesign visual já tem 2 de 5 fases completas. Mapas mentais, questões, simulador de anamnese, contexto por professor e compartilhamento em grupo fazem parte do planejamento e ainda não foram implementados. Não é projeto comercial: nasceu de um problema real da minha namorada e meu ao mesmo tempo, e segue sendo os dois ao mesmo tempo.' },
      ],
    },
    en: {
      name: 'MediStudy',
      status: 'In active development',
      blocks: [
        { t: 'p', text: "I've always been fascinated by AI and what it's really capable of. One day I saw my girlfriend opening more than 15 different tools just to get through one study session: Claude for questions, Anki for flashcards, NotebookLM for organizing notes, three separate tools solving one single problem. I thought: why not build one that covers all of that, shaped exactly to how she studies, and to how she studies with her friends?" },
        { t: 'gallery', label: 'How it looks today', items: [
          { src: 'screens/01-login.webp', caption: 'MediStudy login screen' },
          { src: 'screens/02-home.png', caption: 'Home: sidebar, daily mission and tool grid with real stats' },
          { src: 'screens/03-flashcards.png', caption: 'Flashcards: flipped review card, with the stats panel' },
          { src: 'screens/04-casos-clinicos.png', caption: 'Clinical Cases: an AI-generated case with its options' },
        ] },
        { t: 'h2', text: 'What I have built so far' },
        { t: 'p', text: "The base is already up: spaced-repetition flashcards that actually work (each card's ease factor goes up or down with every answer, changing when it comes back around), an Anki deck importer, two review modes built around her real time, a 5-minute quick review before class and a night-before-the-exam mode that goes through the whole subject from hardest to easiest. The clinical cases are genuinely AI-generated, from a chosen subject, with multiple-choice options, an explanation for the right answer, and a saved history of right/wrong answers. On top of that: an exam calendar with a required-grade calculator, and an evolution history shown as charts." },
        { t: 'p', text: "The architecture piece I found most interesting to solve so far was keeping the AI call out of the browser: clinical cases go through a Supabase function before reaching the AI, so the access key never gets exposed on the published site. It's not flashy for the person using it, but it's the difference between a project that only works on my machine and one that actually works for her, every day." },
        { t: 'diagram', label: 'How the architecture works today', nodes: [
          { title: 'Student action', desc: "E.g.: requesting a clinical case for a subject" },
          { title: 'Supabase function', desc: 'Receives the request, keeps the AI key safe' },
          { title: 'AI generates content', desc: 'Groq, Kimi K2 model, returns the clinical case' },
          { title: 'Validation', desc: "Response format is checked before saving" },
          { title: 'Database', desc: "Case and answer history saved for the student" },
        ] },
        { t: 'h2', text: 'Where group sharing comes in (future vision)' },
        { t: 'p', text: "None of this exists yet, it's the next layer I want to build: the plan was built around groups from the start, because that's how she really studies, with friends, on a call. The idea is for a student to generate a clinical case and pull the group in to discuss it inside the app itself, or to upload a class/exam PDF and have that material become context tied to that class's professor, so the next student in the same class already gets that history ready-made. Today this is design, not code." },
        { t: 'h2', text: 'An estimate of what this means in practice' },
        { t: 'visual', label: 'Before / After', text: 'To put together a clinical case the way she used to: a prompt on ChatGPT, copy it to the group on WhatsApp, sometimes paste it into another AI to review. That easily took 10 to 15 minutes per case. Inside MediStudy, that flow drops to under a minute, without switching tabs.' },
        { t: 'visual', label: 'Before / After', text: "A practice exam specific to one professor would today have to be put together by hand, gathering material manually, which would easily take over an hour. With that professor's history already built up, it becomes a matter of seconds." },
        { t: 'h2', text: 'Cost engineering, today and for when sharing exists' },
        { t: 'p', text: "I already think about this in the one AI call that exists today: clinical cases go through Groq, which has a generous free tier, and I keep Claude reserved for a feature that actually justifies the cost, outside that free tier, instead of defaulting to it for everything that needs AI. Once group sharing exists, this gets even more necessary: if every time someone requested a practice exam the AI had to re-read a professor's entire PDF history from scratch, token usage would explode fast. That's why I already think of the database not just as a place to store data, but as part of the cost strategy: summarize and index the material once, store the summary, and only re-read the full PDF when strictly necessary." },
        { t: 'p', text: "The vision is to go further than what I already use: a routing layer of my own deciding in real time which among several LLMs should answer each request, always optimizing for cost." },
        { t: 'vision', text: "The multi-AI orchestration layer is still in the design phase, not in code." },
        { t: 'h2', text: 'The hard part' },
        { t: 'p', text: "Designing this wasn't just about deciding on features, it was about deciding what the screen shows and what it hides. In the first version I wanted everything visible: charts, numbers, progress bars. I realized that worked against the reason the project exists, which is to simplify, not add another layer of decisions for someone already overwhelmed studying for an exam. I changed the logic to reduce decisions instead of piling up information on the screen." },
        { t: 'h2', text: 'Where it stands today' },
        { t: 'status', text: "In active development, with several tools already in real use: login, home, spaced-repetition flashcards with an Anki importer, AI-generated clinical cases, an exam calendar, grade calculation and an evolution history shown as charts. Over 150 automated tests cover the business logic, and the visual redesign already has 2 of 5 phases complete. Mind maps, questions, an anamnesis simulator, per-professor context and group sharing are part of the roadmap and haven't been implemented yet. It isn't a commercial project: it came from a real problem my girlfriend and I share at the same time, and it stays being both of ours at once." },
      ],
    },
  },

  candidatrack: {
    slug: 'candidatrack',
    order: 2,
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="7" y="7" width="10" height="10" rx="1.5"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>',
    accent: '#3b82f6',
    accent2: '#3b82f6',
    typeBadge: { pt: 'IA + Backend', en: 'AI + Backend' },
    hook: { pt: 'Currículo, portfólio e vaga comparados em segundos, não em planilha.', en: 'Résumé, portfolio and job posting compared in seconds, not in a spreadsheet.' },
    cardMetric: { pt: 'Cerca de 60 vagas já rodadas pelo score de compatibilidade.', en: 'About 60 job postings already run through the compatibility score.' },
    // rodape oculto: o botao dedicado de README (final do conteudo) ja leva pro mesmo repo
    link: { type: 'hidden' },
    readme: 'https://github.com/RyanDua11/candidatrack',
    intro: {
      pt: {
        motivation: 'Enquanto buscava minha própria vaga, via post atrás de post de gente na mesma situação: currículo genérico, vaga que não bate com o perfil, tempo perdido lendo descrição que não ia dar em nada. Construí o CandidaTrack pra resolver isso com dado, não com achismo.',
        built: 'Extração e estruturação automática de currículo, web scraping de vaga, e um score de compatibilidade ponderado entre o que a vaga pede e o que eu tenho. Um chat consultivo por vaga, rodando LLaMA 70B via Groq, ajuda a entender onde o perfil bate ou não bate com o que foi pedido.',
        numbers: 'Já rodei cerca de 60 vagas pelo score de compatibilidade. Uso até hoje na minha própria busca.',
      },
      en: {
        motivation: "While looking for my own job, I saw post after post from people in the same situation: a generic résumé, a job that didn't match the profile, time lost reading a description that was going nowhere. I built CandidaTrack to solve this with data, not with guesswork.",
        built: "Automatic résumé extraction and structuring, job posting scraping, and a compatibility score weighted between what the job asks for and what I have. A consultative chat per job, running LLaMA 70B via Groq, helps understand where the profile matches or doesn't match what was requested.",
        numbers: "I've already run about 60 job postings through the compatibility score. I still use it in my own job search today.",
      },
    },
    pt: {
      name: 'CandidaTrack',
      status: 'Em uso ativo',
      blocks: [
        { t: 'p', text: 'Esse foi meu segundo projeto, e nasceu de um problema que eu mesmo tava vivendo. Eu estava me candidatando a várias vagas ao mesmo tempo e perdi o controle: não sabia mais onde já tinha me candidatado, em que status tava cada processo, e não tinha jeito rápido de comparar meu currículo com o que cada vaga pedia de verdade. Planilha não dava conta. Então construí a solução.' },
        { t: 'gallery', label: 'Como está hoje', items: [
          { src: 'screens/image.png', caption: 'Painel principal: currículo e certificações centralizados' },
          { src: 'screens/image-1.png', caption: 'Upload de currículo e vínculo com GitHub' },
          { src: 'screens/image-2.png', caption: 'Análise automática de vaga via scraping' },
          { src: 'screens/image-3.png', caption: 'Score de compatibilidade entre currículo e vaga' },
          { src: 'screens/image-6.png', caption: 'Registro e acompanhamento de candidaturas' },
        ] },
        { t: 'h2', text: 'O que eu construí' },
        { t: 'p', text: 'O sistema centraliza toda candidatura: empresa, cargo, plataforma, status, com edição inline sem reload de página. Faço upload do currículo em PDF ou DOCX e o sistema extrai o texto sozinho. Colo o link de uma vaga e o sistema faz scraping automático pra puxar título, empresa, requisitos obrigatórios e desejáveis. Se o site bloquear o scraping (o que acontece bastante com portais corporativos e o LinkedIn), o campo de texto aparece automaticamente pra eu colar manualmente, sem travar o fluxo.' },
        { t: 'p', text: 'O coração do projeto é o comparador: ele cruza meu currículo, minhas certificações e meu GitHub com os requisitos da vaga, e devolve um score de compatibilidade, com peso maior pros requisitos obrigatórios que pros desejáveis. E não é comparação de texto exato: o sistema entende equivalência semântica de verdade: "cursando ADS" conta como atendimento pra "Superior em andamento em Sistemas de Informação ou afins", por exemplo. Depois de analisar qualquer vaga, abre um chat consultivo com IA que já sabe todo o contexto e responde perguntas tipo "vale a pena me candidatar?" ou "o que eu reforço nessa entrevista?".' },
        { t: 'diagram', label: 'Como a arquitetura funciona', nodes: [
          { title: 'Upload de currículo', desc: 'PDF ou DOCX, texto extraído automaticamente' },
          { title: 'Scraping da vaga', desc: 'Título, empresa e requisitos extraídos do link (fallback manual se bloqueado)' },
          { title: 'Comparador semântico', desc: 'Cruza currículo, certificações e GitHub com os requisitos' },
          { title: 'Score de compatibilidade', desc: 'Peso maior pros requisitos obrigatórios' },
          { title: 'Chat consultivo', desc: 'LLaMA 70B via Groq, já com o contexto da vaga carregado' },
        ] },
        { t: 'h2', text: 'Engenharia de custo aplicada aqui também' },
        { t: 'p', text: 'Uso dois modelos de propósito diferente: o mais leve e rápido pra extração e comparação, que são tarefas estruturadas onde não compensa pagar mais caro, e o modelo maior só no chat consultivo, onde a resposta elaborada realmente justifica o custo extra. É a mesma lógica que aplico em outros projetos meus: gastar mais só na parte que exige mais, nunca por padrão.' },
        { t: 'h2', text: 'O que isso substitui' },
        { t: 'visual', label: 'Antes / Depois', text: 'Sem o CandidaTrack: candidatura espalhada em planilha ou memória, sem noção real de compatibilidade até a entrevista acontecer (ou não acontecer). Com o CandidaTrack: currículo e vaga comparados automaticamente, com percentual de compatibilidade na hora, e um consultor de IA disponível pra tirar dúvida específica daquela vaga.' },
        { t: 'h2', text: 'Dificuldades reais que resolvi' },
        { t: 'p', text: 'A IA tinha o hábito de quebrar requisito composto tipo "Sistemas de Informação, Ciência da Computação ou afins" em três itens separados, distorcendo o score. Resolvi com instrução explícita no prompt pra tratar isso como uma exigência só. O comparador inicial também marcava "falta" pra tudo que não fosse menção textual idêntica. Resolvi ensinando a IA a fazer equivalência semântica de verdade, com exemplo concreto no prompt. Também enfrentei scraping bloqueado por sites que detectam bot (resolvido com o fallback manual) e um bug de histórico que só carregava depois de analisar uma vaga nova, nunca ao abrir a página pela primeira vez.' },
        { t: 'h2', text: 'Decisões técnicas conscientes' },
        { t: 'p', text: 'O chat não guarda histórico no banco, vive na memória da sessão e reseta a cada vaga nova, porque não faz sentido persistir uma conversa que é contextual por natureza. O currículo entra truncado em 1500 caracteres no chat pra não estourar o contexto sem perder o que importa. As migrations de banco são ALTER TABLE automático no início da aplicação, sem ferramenta externa. Suficiente e mais rápido de manter pra esse tamanho de projeto.' },
        { t: 'h2', text: 'Onde está hoje' },
        { t: 'status', text: 'Em uso ativo. É a ferramenta que eu mesmo uso pra gerenciar minha busca de vaga agora. Meu primeiro projeto foi uma To-Do List API em Java com Spring Boot, PostgreSQL e Docker, onde aprendi na prática os fundamentos de backend e persistência de dados antes de partir pra esse.' },
      ],
    },
    en: {
      name: 'CandidaTrack',
      status: 'Actively in use',
      blocks: [
        { t: 'p', text: "This was my second project, and it came from a problem I was living myself. I was applying to several jobs at once and lost track: I no longer knew where I'd already applied, what status each process was in, and had no quick way to compare my résumé against what each job actually asked for. A spreadsheet couldn't keep up. So I built the solution." },
        { t: 'gallery', label: 'How it looks today', items: [
          { src: 'screens/image.png', caption: 'Main panel: résumé and certifications centralized' },
          { src: 'screens/image-1.png', caption: 'Résumé upload and GitHub link' },
          { src: 'screens/image-2.png', caption: 'Automatic job posting analysis via scraping' },
          { src: 'screens/image-3.png', caption: 'Compatibility score between résumé and job posting' },
          { src: 'screens/image-6.png', caption: 'Application tracking and logging' },
        ] },
        { t: 'h2', text: 'What I built' },
        { t: 'p', text: 'The system centralizes every application: company, role, platform, status, with inline editing and no page reload. I upload my résumé as PDF or DOCX and the system extracts the text on its own. I paste a job link and the system scrapes it automatically to pull the title, company, required and preferred requirements. If the site blocks scraping (which happens a lot with corporate portals and LinkedIn), a text field appears automatically for me to paste it manually, without breaking the flow.' },
        { t: 'p', text: 'The heart of the project is the comparator: it cross-references my résumé, my certifications and my GitHub against the job requirements, and returns a compatibility score, weighting required requirements higher than preferred ones. And it isn\'t exact-text matching: the system understands real semantic equivalence, "currently studying Systems Analysis and Development" counts toward "Bachelor\'s in progress in Information Systems or related field," for example. After analyzing any job, it opens a consultative AI chat that already knows the full context and answers questions like "is it worth applying?" or "what should I reinforce for this interview?"' },
        { t: 'diagram', label: 'How the architecture works', nodes: [
          { title: 'Résumé upload', desc: 'PDF or DOCX, text extracted automatically' },
          { title: 'Job scraping', desc: 'Title, company and requirements pulled from the link (manual fallback if blocked)' },
          { title: 'Semantic comparator', desc: 'Cross-references résumé, certifications and GitHub against requirements' },
          { title: 'Compatibility score', desc: 'Required requirements weighted higher' },
          { title: 'Consultative chat', desc: 'LLaMA 70B via Groq, already loaded with the job’s context' },
        ] },
        { t: 'h2', text: 'Cost engineering applied here too' },
        { t: 'p', text: "I use two models for different purposes: a lighter, faster one for extraction and comparison, which are structured tasks where paying more doesn't pay off, and the larger model only in the consultative chat, where the elaborate answer actually justifies the extra cost. It's the same logic I apply across my other projects: spend more only on the part that demands more, never by default." },
        { t: 'h2', text: 'What this replaces' },
        { t: 'visual', label: 'Before / After', text: "Without CandidaTrack: applications scattered across a spreadsheet or memory, with no real sense of compatibility until the interview happens (or doesn't). With CandidaTrack: résumé and job posting compared automatically, with an instant compatibility percentage, and an AI consultant available for questions specific to that job." },
        { t: 'h2', text: 'Real problems I solved' },
        { t: 'p', text: 'The AI had a habit of breaking a compound requirement like "Information Systems, Computer Science or related field" into three separate items, distorting the score. I fixed it with an explicit prompt instruction to treat that as a single requirement. The initial comparator also flagged "missing" for anything that wasn\'t an identical textual mention, I fixed it by teaching the AI to do real semantic equivalence, with a concrete example in the prompt. I also dealt with scraping blocked by bot-detecting sites (solved with the manual fallback) and a history bug that only loaded after analyzing a new job, never when opening the page for the first time.' },
        { t: 'h2', text: 'Deliberate technical decisions' },
        { t: 'p', text: "The chat doesn't keep history in the database, it lives in session memory and resets with every new job, because it doesn't make sense to persist a conversation that's contextual by nature. The résumé goes into the chat truncated at 1500 characters so it doesn't blow the context window without losing what matters. Database migrations are automatic ALTER TABLE statements at application startup, no external tool, good enough and faster to maintain for a project this size." },
        { t: 'h2', text: 'Where it stands today' },
        { t: 'status', text: "Actively in use, it's the tool I use myself to manage my own job search right now. My first project was a To-Do List API in Java with Spring Boot, PostgreSQL and Docker, where I learned backend fundamentals and data persistence hands-on before moving on to this one." },
      ],
    },
  },

  gloway: {
    slug: 'gloway',
    order: 3,
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21s-7-6.2-7-11.5A7 7 0 0119 9.5C19 14.8 12 21 12 21z"/><circle cx="12" cy="9.5" r="2.5"/></svg>',
    accent: '#14b8a6',
    accent2: '#14b8a6',
    typeBadge: { pt: 'Produto completo', en: 'Full product' },
    hook: { pt: '15 usuários reais, validado no SEBRAE.', en: 'Validated by 15 real users, presented at SEBRAE.' },
    cardMetric: { pt: '15 usuários reais, validado no SEBRAE.', en: 'Validated by 15 real users, presented at SEBRAE.' },
    readme: 'https://github.com/RyanDua11/gloway-tour',
    link: { type: 'external', url: 'https://glowaytour.online', label: { pt: 'Site no ar', en: 'Live site' } },
    intro: {
      pt: {
        motivation: 'Turista chega em Vitória sem saber pra onde ir, morador nunca conheceu metade da própria cidade, e todo guia turístico que eu via era só lista de ponto, sem inteligência nenhuma por trás.',
        built: 'Um roteiro que cruza orçamento, segurança, acessibilidade e contexto pessoal, junto com atlas de qualidade urbana avaliado pelos próprios usuários. Em vez de abrir dez abas pra montar uma viagem, o GloWay entrega isso pronto.',
        numbers: '15 usuários reais testaram, 13 sessões simultâneas ao vivo, custo de infraestrutura abaixo de R$0,005 por roteiro gerado, projeto apresentado e validado pelo SEBRAE.',
      },
      en: {
        motivation: "A tourist arrives in Vitória with no idea where to go, a resident never got to know half of their own city, and every travel guide I saw was just a list of spots, with no intelligence behind it.",
        built: "An itinerary that cross-references budget, safety, accessibility and personal context, together with an urban quality atlas rated by the users themselves. Instead of opening ten tabs to put a trip together, GloWay delivers it ready.",
        numbers: "15 real users tested it, 13 simultaneous live sessions, infrastructure cost under R$0.005 per generated itinerary, project presented and validated at SEBRAE.",
      },
    },
    pt: {
      name: 'GloWay',
      status: 'Validado, protótipo funcional no ar',
      blocks: [
        { t: 'p', text: 'Vitória tem turista chegando sem saber pra onde ir de verdade, e morador que vive na própria cidade sem enxergar metade dela. Todo guia turístico que eu via era só uma lista de pontos, sem nenhuma inteligência por trás. Foi esse problema que ninguém tinha resolvido direito que me fez começar o GloWay.' },
        { t: 'gallery', label: 'Como era o produto', items: [
          { src: 'screens/01-home.webp', caption: 'Home do GloWay: clima em tempo real e atalhos pra Roteiro IA' },
          { src: 'screens/03-atlas.png', caption: 'Atlas de memórias: mapa 3D com localização em tempo real' },
          { src: 'screens/05-pride.webp', caption: 'GloWay Pride: locais verificados como seguros pra comunidade LGBT+' },
          { src: 'screens/07-velo.webp', caption: 'Velô: monitoramento em tempo real das estações de bike-sharing' },
          { src: 'screens/08-roteiro-ia.png', caption: 'Neuro-Planner: configuração do roteiro por IA' },
        ] },
        { t: 'h2', text: 'O que eu construí' },
        { t: 'p', text: 'O coração do produto era o Neuro-Planner. Você escolhia se queria o roteiro por horas ou por dias inteiros, definia um orçamento, e a IA buscava tudo dentro daquele valor, incluindo mobilidade. Dava pra filtrar por acessibilidade, por pet friendly, por local seguro pra comunidade LGBT+, ou pedir um roteiro pensado especificamente pra isso. Cobria de passeio náutico a expedição de trilha, cinema a passeio de caiaque. A IA ainda checava o clima e avisava, e se a pessoa quisesse mudar tudo em cima da hora, dava pra ajustar o roteiro na mão, sem perder o que já tinha sido planejado. Quando o roteiro incluía reserva (hospedagem, passeio, voo), o app direcionava direto pro site certo pra fechar o pagamento ou ver mais detalhes.' },
        { t: 'p', text: 'Construí também um Atlas de memórias em 3D, onde o próprio usuário avaliava iluminação, segurança e mobilidade do lugar onde estava, criando um mapa de qualidade urbana feito pela cidade, não por burocracia. E um monitor de bike-sharing em tempo real, o Velô, além de gamificação e ferramentas offline. Fui até o fim: integrei pagamento via Stripe em modo live, não sandbox, porque queria validar de verdade, não só maquete.' },
        { t: 'diagram', label: 'Como a arquitetura funciona', nodes: [
          { title: 'Orçamento + contexto', desc: 'Acessibilidade, pet friendly, comunidade LGBT+' },
          { title: 'Neuro-Planner (IA)', desc: 'Cruza clima, mobilidade e valor disponível' },
          { title: 'Atlas de qualidade urbana', desc: 'Iluminação e segurança avaliadas pelos próprios usuários' },
          { title: 'Roteiro pronto', desc: 'Local, valor estimado e avaliação, ajustável na hora' },
          { title: 'Reserva (Stripe live)', desc: 'Direciona pro pagamento quando o roteiro inclui reserva' },
        ] },
        { t: 'h2', text: 'O que isso substitui' },
        { t: 'visual', label: 'Antes / Depois', text: 'Sem o GloWay, montar essa mesma viagem significa abrir dez abas: pesquisar hospedagem num site, comparar preço no outro, procurar comentário de segurança do bairro num terceiro, tentar achar se aquele lugar é acessível ou pet friendly em algum lugar perdido de review. Isso facilmente leva dias de pesquisa espalhada. O Neuro-Planner entregava local, valor estimado, avaliação e comentário prontos, dentro do orçamento definido, em questão de segundos, ou algumas horas se a pessoa quisesse revisar tudo com calma antes de fechar.' },
        { t: 'h2', text: 'O que eu validei' },
        { t: 'stats', items: [
          { num: '15', label: 'usuários reais testaram o produto' },
          { num: '13', label: 'sessões simultâneas ao vivo' },
          { num: '< R$0,005', label: 'de custo de infraestrutura por roteiro gerado por IA' },
        ] },
        { t: 'p', text: 'Rodei o produto com 15 usuários reais, cheguei a ter 13 sessões simultâneas ao vivo, e apresentei o projeto no SEBRAE. O custo de infraestrutura ficou abaixo de R$0,005 por roteiro gerado por IA, o que na prática significa que gerar mil roteiros custava menos de R$5 de infraestrutura. Provava que o modelo era sustentável em escala, não só bonito em demonstração.' },
        { t: 'h2', text: 'Por que parou' },
        { t: 'p', text: 'O produto funcionava, e continua funcionando: o protótipo ainda está de pé no Google AI Studio, onde foi construído. O que faltou foi verba de marketing pra crescer a base de usuários, não limitação técnica. Sigo aberto a retomar no futuro.' },
        { t: 'h2', text: 'Por que acho que ela pode ir longe' },
        { t: 'p', text: 'O modelo foi desenhado pra ser modular desde o início: uma plataforma pensada pra funcionar em qualquer cidade, não só Vitória, com custo por usuário baixo o bastante pra escalar sem virar problema financeiro. Também via espaço pro pequeno comerciante local se conectar com quem visita a cidade, do mesmo jeito que uma grande marca poderia, um caminho de crescimento que vai do pequeno negócio ao grande player, sem precisar refazer o produto do zero em cada etapa.' },
      ],
    },
    en: {
      name: 'GloWay',
      status: 'Validated, working prototype still live',
      blocks: [
        { t: 'p', text: "Vitória has tourists arriving with no real idea where to go, and residents living in their own city without seeing half of it. Every travel guide I saw was just a list of spots, with no intelligence behind it. That was the problem nobody had really solved, and it's what got me started on GloWay." },
        { t: 'gallery', label: 'What the product looked like', items: [
          { src: 'screens/01-home.webp', caption: 'GloWay home: real-time weather and Itinerary AI shortcuts' },
          { src: 'screens/03-atlas.png', caption: 'Memory Atlas: 3D map with real-time location' },
          { src: 'screens/05-pride.webp', caption: 'GloWay Pride: verified LGBT+-safe locations' },
          { src: 'screens/07-velo.webp', caption: 'Velô: real-time bike-sharing station monitoring' },
          { src: 'screens/08-roteiro-ia.png', caption: 'Neuro-Planner: AI itinerary configuration' },
        ] },
        { t: 'h2', text: 'What I built' },
        { t: 'p', text: "The heart of the product was the Neuro-Planner. You'd choose whether you wanted the itinerary by the hour or for full days, set a budget, and the AI searched for everything within that value, including transportation. You could filter by accessibility, pet-friendliness, LGBT+-safe locations, or ask for an itinerary built specifically around that. It covered everything from boat trips to hiking expeditions, movies to kayaking. The AI also checked the weather and would warn you, and if you wanted to change everything last minute, you could adjust the itinerary by hand without losing what had already been planned. When the itinerary included a booking (lodging, a tour, a flight), the app routed straight to the right site to complete the payment or see more details." },
        { t: 'p', text: "I also built a 3D memory Atlas, where the user themself rated the lighting, safety and accessibility of the place they were at, creating a map of urban quality made by the city, not by bureaucracy. And a real-time bike-sharing monitor, Velô, plus gamification and offline tools. I went all the way: I integrated Stripe payments in live mode, not sandbox, because I wanted to validate it for real, not just as a mockup." },
        { t: 'diagram', label: 'How the architecture works', nodes: [
          { title: 'Budget + context', desc: 'Accessibility, pet-friendliness, LGBT+ community' },
          { title: 'Neuro-Planner (AI)', desc: 'Cross-references weather, mobility and available budget' },
          { title: 'Urban quality Atlas', desc: 'Lighting and safety rated by the users themselves' },
          { title: 'Ready itinerary', desc: 'Location, estimated cost and rating, adjustable on the spot' },
          { title: 'Booking (Stripe live)', desc: 'Routes to payment when the itinerary includes a booking' },
        ] },
        { t: 'h2', text: 'What this replaces' },
        { t: 'visual', label: 'Before / After', text: "Without GloWay, putting together that same trip means opening ten tabs: researching lodging on one site, comparing prices on another, hunting for neighborhood safety comments on a third, trying to find whether that place is accessible or pet-friendly buried in some review somewhere. That easily takes days of scattered research. The Neuro-Planner delivered the place, an estimated cost, ratings and comments ready, within the defined budget, in a matter of seconds, or a few hours if the person wanted to calmly review everything before booking." },
        { t: 'h2', text: 'What I validated' },
        { t: 'stats', items: [
          { num: '15', label: 'real users tested the product' },
          { num: '13', label: 'simultaneous live sessions' },
          { num: '< R$0.005', label: 'infrastructure cost per AI-generated itinerary' },
        ] },
        { t: 'p', text: 'I ran the product with 15 real users, reached 13 simultaneous live sessions, and presented the project at SEBRAE (the Brazilian small-business support agency). Infrastructure cost stayed under R$0.005 per AI-generated itinerary, which in practice means generating a thousand itineraries cost less than R$5 in infrastructure. It proved the model was sustainable at scale, not just nice-looking in a demo.' },
        { t: 'h2', text: 'Why it stopped' },
        { t: 'p', text: "The product worked, and still works: the prototype is still live on Google AI Studio, where it was built. What was missing was marketing budget to grow the user base, not a technical limitation. I remain open to picking it back up in the future." },
        { t: 'h2', text: 'Why I think it can go far' },
        { t: 'p', text: "The model was designed to be modular from the start: a platform meant to work in any city, not just Vitória, with a low enough cost per user to scale without becoming a financial problem. I also saw room for small local businesses to connect with visitors the same way a big brand could, a growth path that goes from small business to major player without needing to rebuild the product from scratch at each stage." },
      ],
    },
  },

  ledgerx: {
    slug: 'ledgerx',
    order: 4,
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 17l5-5 4 4 8-8M20 8v5M20 8h-5"/></svg>',
    accent: '#f59e0b',
    accent2: '#22c55e',
    typeBadge: { pt: 'PostgreSQL avançado', en: 'Advanced PostgreSQL' },
    hook: { pt: 'PostgreSQL avançado organizando minha vida financeira de verdade.', en: 'Advanced PostgreSQL organizing my real financial life.' },
    cardMetric: { pt: 'Usado com dado financeiro real por 3 pessoas.', en: 'Used with real financial data by 3 people.' },
    // rodape oculto: o botao dedicado de README (final do conteudo) ja leva pro mesmo repo
    link: { type: 'hidden' },
    readme: 'https://github.com/RyanDua11/ledgerx',
    intro: {
      pt: {
        motivation: 'Eu e alguns amigos tínhamos o mesmo problema: gastar sem perceber, sem nenhum alerta até a conta já estar no vermelho. Aproveitei esse problema real pra estudar PostgreSQL avançado e Docker a fundo, construindo o LedgerX pra resolver isso com dado, não com força de vontade.',
        built: 'Um score de saúde financeira calculado direto no banco, usando window functions, CTEs e materialized views. Alertas automáticos disparados por trigger quando o gasto foge do padrão, com audit log completo e exportação de relatório pra Excel.',
        numbers: 'Usado com dado financeiro real por 3 pessoas (eu e dois amigos). Um dos usuários identificou, através dos alertas, um padrão de gasto recorrente que não tinha percebido antes.',
      },
      en: {
        motivation: "A few friends and I had the same problem: spending without noticing, with no alert until the account was already in the red. I used that real problem to study advanced PostgreSQL and Docker in depth, building LedgerX to solve it with data, not with willpower.",
        built: 'A financial health score calculated directly in the database, using window functions, CTEs and materialized views. Automatic alerts fired by a trigger when spending strays from the pattern, with a complete audit log and Excel report export.',
        numbers: 'Used with real financial data by 3 people (me and two friends). One of the users spotted, through the alerts, a recurring spending pattern they hadn\'t noticed before.',
      },
    },
    pt: {
      name: 'LedgerX',
      status: 'Em uso ativo',
      blocks: [
        { t: 'p', text: 'Esse projeto nasceu de pura curiosidade técnica. Eu queria aprender PostgreSQL de verdade, não só o básico de SELECT e JOIN que qualquer curso ensina, e resolvi usar minha própria vida financeira como caso de uso real. Hoje sou eu e mais duas pessoas usando o LedgerX no dia a dia pra organizar gasto.' },
        { t: 'gallery', label: 'Como está hoje', items: [
          { src: 'screens/04-transacoes.png', caption: 'Transações: histórico completo com filtro por tipo e categoria' },
          { src: 'screens/03-metas.png', caption: 'Metas: limite mensal configurável por categoria' },
          { src: 'screens/01-relatorios.png', caption: 'Relatórios: média móvel de 3 meses calculada direto no PostgreSQL' },
        ] },
        { t: 'h2', text: 'O que eu construí' },
        { t: 'p', text: 'A tabela de transações é particionada por mês. Isso significa que, em vez de guardar todo o histórico financeiro numa tabela gigante só, o banco separa fisicamente cada mês em sua própria partição. Na prática, isso evita que uma consulta simples, tipo "quanto eu gastei em março", precise varrer anos de dado irrelevante pra achar um mês específico.' },
        { t: 'p', text: 'Tem duas materialized views: uma resume receita, despesa e saldo por mês, outra cruza gasto por categoria com o percentual do limite definido. Diferente de uma view comum, que recalcula tudo toda vez que é consultada, a materialized view guarda o resultado pronto. Abrir o relatório é instantâneo, não um recálculo pesado a cada clique.' },
        { t: 'p', text: 'Uso window functions pra gerar dois relatórios que view comum não resolve sozinha: um comparativo mês a mês por categoria usando LAG (quanto eu gastei em mercado esse mês comparado ao mês passado, categoria por categoria), e uma média móvel de três meses pra suavizar gasto e mostrar tendência real, não só o número isolado de um mês bom ou ruim.' },
        { t: 'p', text: 'Tenho full-text search em português rodando sobre a descrição de cada transação, atualizado automaticamente por trigger toda vez que insiro ou edito um lançamento. E o banco toma decisão sozinho: um trigger dispara um alerta automático assim que uma categoria bate 80% do limite mensal que eu defini. Todo INSERT, UPDATE e DELETE de transação fica registrado num audit log completo, em JSONB, guardando o valor antes e depois da mudança.' },
        { t: 'diagram', label: 'Como a arquitetura funciona', nodes: [
          { title: 'Transação (INSERT/UPDATE)', desc: 'Trigger dispara em tempo real' },
          { title: 'Partição mensal', desc: 'Cada mês isolado fisicamente na própria partição' },
          { title: 'Materialized views', desc: 'Resumo mensal e limite por categoria pré-calculados' },
          { title: 'Window functions', desc: 'LAG mês a mês e média móvel de 3 meses' },
          { title: 'Alerta + audit log', desc: 'Trigger de 80% do limite e histórico completo em JSONB' },
        ] },
        { t: 'h2', text: 'O que isso substitui' },
        { t: 'visual', label: 'Antes / Depois', text: 'Sem o LedgerX: planilha manual, sem alerta de limite, sem comparação automática entre meses. Com o LedgerX: alerta automático antes de estourar o orçamento, comparação de tendência de gasto pronta, e histórico auditável de cada edição, sem esforço manual nenhum.' },
        { t: 'h2', text: 'Por que fiz assim' },
        { t: 'p', text: 'Cada decisão técnica aqui tem um motivo de performance ou de negócio por trás, não foi escolha aleatória de "porque é avançado". Particionar por mês existe porque relatório financeiro quase sempre filtra por período. Materialized view existe porque dashboard tem que abrir na hora, não depois de recalcular tudo. O trigger de 80% existe porque de nada adianta um relatório bonito se ninguém olha ele a tempo de evitar estourar o orçamento.' },
        { t: 'h2', text: 'Onde está hoje' },
        { t: 'status', text: 'Em uso ativo, com exportação de relatório em Excel com gráfico via Chart.js. Continuo evoluindo o projeto enquanto aprendo mais sobre PostgreSQL avançado. É o projeto que eu mais mexo por puro interesse técnico, não por necessidade de portfólio.' },
      ],
    },
    en: {
      name: 'LedgerX',
      status: 'Actively in use',
      blocks: [
        { t: 'p', text: 'This project came out of pure technical curiosity. I wanted to really learn PostgreSQL, not just the basic SELECT and JOIN that any course teaches, so I decided to use my own financial life as a real use case. Today it\'s me and two other people using LedgerX day to day to organize spending.' },
        { t: 'gallery', label: 'How it looks today', items: [
          { src: 'screens/04-transacoes.png', caption: 'Transactions: full history with type and category filters' },
          { src: 'screens/03-metas.png', caption: 'Goals: configurable monthly limit per category' },
          { src: 'screens/01-relatorios.png', caption: '3-month moving average calculated directly in PostgreSQL' },
        ] },
        { t: 'h2', text: 'What I built' },
        { t: 'p', text: 'The transactions table is partitioned by month. That means instead of storing the entire financial history in one giant table, the database physically separates each month into its own partition. In practice, that keeps a simple query, like "how much did I spend in March," from having to scan years of irrelevant data to find one specific month.' },
        { t: 'p', text: "There are two materialized views: one summarizes income, expenses and balance per month, the other cross-references spending by category with the percentage of the defined limit. Unlike a regular view, which recalculates everything every time it's queried, a materialized view stores the finished result, so opening the report is instant, not a heavy recalculation on every click." },
        { t: 'p', text: "I use window functions to generate two reports a regular view can't solve on its own: a month-over-month comparison by category using LAG (how much I spent on groceries this month compared to last month, category by category), and a three-month moving average to smooth out spending and show real trend, not just an isolated number from one good or bad month." },
        { t: 'p', text: "I have full-text search in Portuguese running over each transaction's description, updated automatically by a trigger every time I insert or edit an entry. And the database makes decisions on its own: a trigger fires an automatic alert as soon as a category hits 80% of the monthly limit I set. Every INSERT, UPDATE and DELETE on a transaction gets logged in a complete audit log, in JSONB, storing the value before and after the change." },
        { t: 'diagram', label: 'How the architecture works', nodes: [
          { title: 'Transaction (INSERT/UPDATE)', desc: 'Trigger fires in real time' },
          { title: 'Monthly partition', desc: 'Each month physically isolated in its own partition' },
          { title: 'Materialized views', desc: 'Monthly summary and per-category limit pre-calculated' },
          { title: 'Window functions', desc: 'Month-over-month LAG and 3-month moving average' },
          { title: 'Alert + audit log', desc: '80% limit trigger and full history in JSONB' },
        ] },
        { t: 'h2', text: 'What this replaces' },
        { t: 'visual', label: 'Before / After', text: 'Without LedgerX: a manual spreadsheet, no limit alerts, no automatic comparison between months. With LedgerX: an automatic alert before going over budget, ready-made spending trend comparisons, and an auditable history of every edit, with zero manual effort.' },
        { t: 'h2', text: 'Why I built it this way' },
        { t: 'p', text: 'Every technical decision here has a performance or business reason behind it, none of it was a random choice made "because it\'s advanced." Partitioning by month exists because financial reports almost always filter by period. The materialized view exists because a dashboard has to open instantly, not after recalculating everything. The 80% trigger exists because a pretty report is worthless if nobody looks at it in time to avoid going over budget.' },
        { t: 'h2', text: 'Where it stands today' },
        { t: 'status', text: "Actively in use, with Excel report export including charts via Chart.js. I keep evolving the project as I learn more about advanced PostgreSQL, it's the project I tinker with most out of pure technical interest, not out of portfolio necessity." },
      ],
    },
  },
};

const PROJECT_ORDER = ['medistudy', 'candidatrack', 'gloway', 'ledgerx'];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROJECTS_CONTENT, PROJECT_ORDER };
}
